export const transrapid =
  'Neujahrsempfang der CSU Wenn Sie vom Hauptbahnhof in Muenchen mit zehn Minuten ohne dass Sie am Flughafen noch einchecken muessen dann starten Sie im Grunde genommen am Flughafen am Hauptbahnhof in Muenchen starten Sie Ihren Flug Zehn Minuten Schauen Sie sich mal die grossen Flughaefen an wenn Sie in Heathrow in London oder sonst wo meine Charles de Gaulle in Frankreich oder in Rom Wenn Sie sich mal die Entfernungen ansehen wenn Sie Frankfurt sich ansehen dann werden Sie feststellen dass zehn Minuten Sie jederzeit locker in Frankfurt brauchen um ihr Gate zu finden Wenn Sie vom Flug vom Hauptbahnhof starten Sie steigen in den Hauptbahnhof ein Sie fahren mit dem Transrapid in zehn Minuten an den Flughafen in an den Flughafen Franz Josef Strauss Dann starten Sie praktisch hier am Hauptbahnhof in Muenchen Das bedeutet natuerlich dass der Hauptbahnhof im Grunde genommen naeher an Bayern an die bayerischen Staedte heranwaechst weil das ja klar ist weil auf dem Hauptbahnhof viele Linien aus Bayern zusammenlaufen'

export const nineteenEightyFour =
  'Nineteen eighty four by George Orwell It was a bright cold day in April and the clocks were striking thirteen Winston Smith his chin nuzzled into his breast in an effort to escape the vile wind slipped quickly through the glass doors of Victory Mansions though not quickly enough to prevent a swirl of gritty dust from entering along with him The hallway smelt of boiled cabbage and old rag mats At one end of it a coloured poster too large for indoor display had been tacked to the wall It depicted simply an enormous face more than a metre wide the face of a man of about forty five with a heavy black moustache and ruggedly handsome features Winston made for the stairs It was no use trying the lift Even at the best of times it was seldom working and at present the electric current was cut off during daylight hours It was part of the economy drive in preparation for Hate Week The flat was seven flights up and Winston who was thirty nine and had a varicose ulcer above his right ankle went slowly resting several time'

export const abschied =
  'Abschied von Rilke Wie hab ich das gefuehlt was Abschied heisst Wie weiss ichs noch ein dunkles unverwundnes grausames Etwas das ein schoen verbundnes noch einmal zeigt und hinhaelt und zerreisst Wie war ich ohne Wehr dem zuzuschauen Das da es mich mich rufend gehen liess Zurueckblieb so als waerens alle Frauen Und dennoch klein und weiss und nichts als dies Ein Winken schon nicht mehr auf mich bezogen Ein leise Weiterwinkendes schon kaum Erklaerbar mehr vielleicht ein Pflaumenbaum Von dem ein Kuckuck hastig abgeflogen Schon kehrt der Saft aus jener Allgemeinheit Die dunkel in den Wurzeln sich erneut Zurueck ans Licht und speist die gruene Reinheit Die unter Rinden noch die Winde scheut Die Innenseite der Natur belebt sich Verheimlichend ein neues Freuet euch Und eines ganzen Jahres Jugend hebt sich Unkenntlich noch ins starrende Gestraeuch Des alten Nussbaums ruehmliche Gestaltung Fuellt sich mit Zukunft aussen grau und kuehl Doch junges Buschwerk zittert vor Verhaltung Unter der kleinen Voegel Vorgefuehl'

export const schiller =
  'an die freude von schiller Freude schoener Goetterfunken Tochter aus Elysium Wir betreten feuertrunken Himmlische dein Heiligtum Deine Zauber binden wieder Was der Mode Schwert geteilt Bettler werden Fuerstenbrueder Wo dein sanfter Fluegel weilt Seid umschlungen Millionen Diesen Kuss der ganzen Welt Brueder ueberm Sternenzelt Muss ein lieber Vater wohnen Wem der grosse Wurf gelungen Eines Freundes Freund zu sein Wer ein holdes Weib errungen Mische seinen Jubel ein Ja wer auch nur eine Seele Sein nennt auf dem Erdenrund Und wers nie gekonnt der stehle Weinend sich aus diesem Bund Was den grossen Ring bewohnet Huldige der Sympathie Zu den Sternen leitet sie Wo der Unbekannte thronet Freude trinken alle Wesen An den Bruesten der Natur Alle Guten alle Boesen Folgen ihrer Rosenspur Kuesse gab sie uns und Reben Einen Freund geprueft im Tod Wollust ward dem Wurm gegeben Und der Cherub steht vor Gott Ihr stuerzt nieder Millionen Ahndest du den Schoepfer Welt Such ihn ueberm Sternenzelt ueber Sternen muss er wohnen'

export const monaLisa = `ffsffsffssfffofffofsfsossofoofofffvffsffffvfvffsfsfffvffffvffvffffffvffvvfffvfffffvffffvfffffffvffffffzffffffffvfffffffffffvffffffzfffffzffzfzvjjvffzfffzffzfzffffzffzffzffzfvvvjdjfffzvffzzffzzfzffzzfzffzzvzzfjrrrfffffzffffffffzfffzzfzfjzhhzzjddrzffzzffzzfzzfzzzzffzzfjzhhzzjrddzffzfzzffzzffffzfhhzfvzzzhzzzjdddffffzzfzffvcffffvfhfvvvzzvjvrdrdvfofzzhzffvovvfcffffjzzzvzzzjjddsvvoffzfffovfovvovvovzzzzzzzdddrofvfffzffffjovffvovjvrzzzzzvjdddrsocffovvcrvovvovfjojrzzfvzvjdrdvcjvcvfcvvscvsvvccvojjvzzzvvdddjscofvcfcoojjjocjvvofrjczzvjvjdddjvfovcvvvfdsovvfffozrrdrjrsvvddddsvofvcofvcvjcfofvffrjjdfzvvfjrjdffvofffffsoocvjvvvdddjjzzzzfjrvddsvjzzvvfvfvvvfvcorrjvzzzzzzvvjdrvfzfvvovvvvfvfvvjjdvzhhzhhzvjjjjdvffzzfvvvvzvvvfjdvvhhhzhhzvvdsjjdvzffzvvvfvvzvvdjzhhzhhzzzzvvzvdddvjvvzvvvffvzdjdvhzzhhhhzvfjjdcvddvvofcvvzzvddjcvvvzzhhzvjsddjdddcvvvvcvzvvzjcjjjjvvfvvvjddvvdddjcovvfvjvvvvddcjjcsvvvsjddjdsvvjdrjzovvfvzzrcjrdjdjvjvcddddjvvvdcjdjjfjfzfvrcjddvdjccjjdjddvjcdddccjzdcjvjcjvdcdjcvjrcjdddjdddrjdcvccvvvcvccvvjddcdjvcdddddddrdddjrojv`
