/*
Hier sind die Strings definiert, die die Grundlage für die verschiedenen Level bilden,
siehe ./index.js
*/

export const transrapid =
  'Wenn Sie vom Hauptbahnhof in Muenchen mit zehn Minuten ohne dass Sie am Flughafen noch einchecken muessen dann starten Sie im Grunde genommen am Flughafen am am Hauptbahnhof in Muenchen starten Sie Ihren Flug Zehn Minuten Schauen Sie sich mal die grossen Flughaefen an wenn Sie in Heathrow in London oder sonst wo meine se Charles de Gaulle in Frankreich oder in aeh in in aeh in Rom Wenn Sie sich mal die Entfernungen ansehen wenn Sie Frankfurt sich ansehen dann werden Sie feststellen dass zehn Minuten Sie jederzeit locker in Frankfurt brauchen um ihr Gate zu finden Wenn Sie vom Flug vom vom Hauptbahnhof starten Sie steigen in den Hauptbahnhof ein Sie fahren mit dem Transrapid in zehn Minuten an den Flughafen in an den Flughafen Franz Josef Strauss Dann starten Sie praktisch hier am Hauptbahnhof in Muenchen Das bedeutet natuerlich dass der Hauptbahnhof im Grunde genommen naeher an Bayern an die bayerischen Staedte heranwaechst weil das ja klar ist weil auf dem Hauptbahnhof viele Linien aus Bayern zusammenlaufen'

export const nineteenEightyFour =
  'It was a bright cold day in April and the clocks were striking thirteen Winston Smith his chin nuzzled into his breast in an effort to escape the vile wind slipped quickly through the glass doors of Victory Mansions though not quickly enough to prevent a swirl of gritty dust from entering along with him The hallway smelt of boiled cabbage and old rag mats At one end of it a coloured poster too large for indoor display had been tacked to the wall It depicted simply an enormous face more than a metre wide the face of a man of about forty five with a heavy black moustache and ruggedly handsome features Winston made for the stairs It was no use trying the lift Even at the best of times it was seldom working and at present the electric current was cut off during daylight hours It was part of the economy drive in preparation for Hate Week The flat was seven flights up and Winston who was thirty nine and had a varicose ulcer above his right ankle went slowly resting several times round the waist of her overalls'

export const jobs =
  'This is the day Ive been looking forward to for two and a half years Every once in a while a revolutionary product comes along that changes everything and Apple has been well first of all ones very fortunate if you get to work on just one of these in your career Apple has been very fortunate Its been able to introduce a few of these into the world in eighty four we introduced the Macintosh It didnt just change Apple It changed the whole computer industry in two thousand one we introduced the first iPod it didnt just change the way we all listen to music it changed the entire music industry today we are introducing three revolutionary products of this class The first one is a widescreen iPod with touch controls The second is a revolutionary mobile phone And the third is a breakthrough Internet communications device So three things a widescreen iPod with touch controls a revolutionary mobile phone and a breakthrough Internet communications device An iPod a phone and an Internet communicator are you getting it'

export const schiller =
  'Freude schoener Goetterfunken Tochter aus Elysium Wir betreten feuertrunken Himmlische dein Heiligtum Deine Zauber binden wieder Was der Mode Schwert geteilt Bettler werden Fuerstenbrueder Wo dein sanfter Fluegel weilt Seid umschlungen Millionen Diesen Kuss der ganzen Welt Brueder ueberm Sternenzelt Muss ein lieber Vater wohnen Wem der grosse Wurf gelungen Eines Freunds Freund zu sein Wer ein holdes Weib errungen Mische seinen Jubel ein Ja wer auch nur eine Seele Sein nennt auf dem Erdenrund Und wers nie gekonnt der stehle Weinend sich aus diesem Bund Was den grossen Ring bewohnet Huldige der Sympathie Zu den Sternen leitet sie Wo der Unbekannte thronet Freude trinken alle Wesen An den Bruesten der Natur Alle Guten alle Boesen Folgen ihrer Rosenspur Kuesse gab sie uns und Reben Einen Freund geprueft im Tod Wollust ward dem Wurm gegeben Und der Cherub steht vor Gott Ihr stuerzt nieder Millionen Ahndest du den Schoepfer Welt Such ihn ueberm Sternenzelt ueber Sternen muss er wohnen Freude heisst die starke Feder'

export const africa =
  'I hear the drums echoing tonight But she hears only whispers of some quiet conversation Shes coming in twelve thirty flight The moonlit wings reflect the stars that guide me towards salvation I stopped an old man along the way Hoping to find some old forgotten words or ancient melodies He turned to me as if to say Hurry boy its waiting there for you Its gonna take a lot to drag me away from you Theres nothing that a hundred men or more could ever do I bless the rains down in Africa Gonna take some time to do the things we never had The wild dogs cry out in the night As they grow restless longing for some solitary company I know that I must do whats right As sure as Kilimanjaro rises like Olympus above the Serengeti I seek to cure whats deep inside frightened of this thing that Ive become Its gonna take a lot to drag me away from you Theres nothing that a hundred men or more could ever do I bless the rains down in Africa Gonna take some time to do the things we never had Hurry boy shes waiting there for you'

export const kennedy =
  'In eighteen years of peace Germans has earned the right to be free including the right to unite their families and their nation in lasting peace with good will to all people So let me ask you as I close to lift your eyes beyond the dangers of today to the hopes of tomorrow beyond the freedom merely of this city of Berlin or your country of Germany to the advance of freedom everywhere beyond the wall to the day of peace with justice beyond yourselves and ourselves to all mankind Freedom is indivisible and when one man is enslaved all are not free When all are free then we can look forward to that day when this city will be joined as one and this country and this great Continent of Europe in a peaceful and hopeful globe When that day finally comes as it will the people of West Berlin can take sober satisfaction in the fact that they were in the front lines for almost two decades All free men wherever they may live are citizens of Berlin and therefore as a free man I take pride in the words Ich bin ein Berliner'

export const reservoirDogs =
  'I dont tip I dont believe in it Dont give me that if she dont make enough money she can quit I dont tip because society says I have to I mean Ill tip if somebody really deserves a tip if they really put forth the effort Ill give them something extra but this tipping automatically its for the birds as far as Im concerned theyre just doing their job She wasnt anything special I ordered coffee weve been here a long fuckin time and shes only filled my cup three times I mean when I order coffee I want it filled six times The words too fucking busy shouldnt be in a waitress vocabulary I mean these ladies arent starvin to death They make minimum wage You know I used to work minimum wage and when I did I wasnt lucky enough to have a job that society deemed tipworthy You know what this is Its the worlds smallest violin playing just for the waitresses So is workin at McDonalds but you dont feel the need to tip them do ya Well why not society says dont tip these guys over here but tip these guys over here Thats bullshit'

export const joker =
  'Want to know how I got these scars My father was a drinker and a fiend And one night he goes off crazier than usual Mommy gets the kitchen knife to defend herself He doesnt like that Not one bit So me watching he takes the knife to her laughing while he does it He turns to me and he says Why so serious He comes at me with the knife Why so serious He sticks the blade in my mouth Lets put a smile on that face And why so serious               Well you look nervous Is it the scars You wanna know how I got em Come here Hey Look at me So I had a wife beautiful like you who tells me I worry too much Who tells me I oughta smile more Who gambles and gets in deep with the sharks Look at me One day they carve her face And we have no money for surgeries She cant take it I just want to see her smile again hmm I just want her to know that I dont care about the scars So I stick a razor in my mouth and do this to myself And you know what She cant stand the sight of me She leaves Now I see the funny side Now Im always smiling'

export const monaLisa =
  'ffsffsffssfffofffofsfsossofoofofffvffsffffvfvffsfsfffvffffvffvffffffvffvvfffvfffffvffffvfffffffvffffffzffffffffvfffffffffffvffffffzfffffzffzfzvjjvffzfffzffzfzffffzffzffzffzfvvvjpjfffzvffzzffzzfzffzzfzffzzvzzfjrrrfffffzffffffffzfffzzfzfjzhhzzjpprzffzzffzzfzzfzzzzffzzfjzhhzzjrppzffzfzzffzzffffzfhhzfvzzzhzzzjpppffffzzfzffvcffffvfhfvvvzzvjvrprpvfofzzhzffvovvfcffffjzzzvzzzjjppsvvoffzfffovfovvovvovzzzzzzzppprofvfffzffffjovffvovjvrzzzzzvjppprsocffovvcrvovvovfjojrzzfvzvjprpvcjvcvfcvvscvsvvccvojjvzzzvvpppjscofvcfcoojjjocjvvofrjczzvjvjpppjvfovcvvvfpsovvfffozrrprjrsvvppppsvofvcofvcvjcfofvffrjjpfzvvfjrjpffvofffffsoocvjvvvpppjjzzzzfjrvppsvjzzvvfvfvvvfvcorrjvzzzzzzvvjprvfzfvvovvvvfvfvvjjpvzhhzhhzvjjjjpvffzzfvvvvzvvvfjpvvhhhzhhzvvpsjjpvzffzvvvfvvzvvpjzhhzhhzzzzvvzvpppvjvvzvvvffvzpjpvhzzhhhhzvfjjpcvppvvofcvvzzvppjcvvvzzhhzvjsppjpppcvvvvcvzvvzjcjjjjvvfvvvjppvvpppjcovvfvjvvvvppcjjcsvvvsjppjpsvvjprjzovvfvzzrcjrpjpjvjvcppppjvvvpcjpjjfjfzfvrcjppvpjccjjpjppvjcpppccjzpcjvjcjvpcpjcvjrcjpppjppprjpcvccvvvcvccvvjppcpjvcppppppprpppjrojv'

export const cheGuevara =
  'UUUUUUUUUURPPPPPPPPPUUUUUUUUUUUUUUUUUUUUPRPPPPBFPPPPPRUUUUUUUUUUUUUUUUUPPPPPPPBBPPPPPPPPRUUUUUUUUUUUUUUPPPPPPPPPPPPPPPPPPRUUUUUUUUUUUUPPPPPPPPPPPPPPPPPPPPPUUUUUUUUUUUPPPPPPPPPPPPPPPPPPPPPPUUUUUUUUUUPPPPFBBBBBBFFPPPPPPPPPUUUUUUUUURPPPWBBBBBBBBBBBFPPPPPPPUUUUUUUURRPPBBBBBBBBBBBBBBPPPPPPRUUUUUUUUPPFBBBBBBBBBBBBBBPPPPPPRUUUUUUURPPFFCBBBBBBCPPPPPPPPPPPRUUUUUUURPPPFPPPPBBFPPPPPPPPPPPPPUUUUUUPPPPYPFPFBBBWPPPPPPPPPPPPPUUUUUPPPPFBFBBBBBBPPBBFPPPPPPPPPUUUUPPPPPFBBBBBBBBFFBBBPPPPPPPPPUUUURPPPPFBBBBBBBBBBBBBBBFPPPPPRUUUURPPPPFBBBBBBWFFBBBBBPPPPPPPPPUUUPPPPPPBBBBBWBFPPFBBFPPPPPPPPPRUUPPPPPPBBBBBBBBFFBBBFPPPPPPPPRUUUPPPPPPFBBBBBWBFPWBBWPPPPPPPPRUUURPPPPPPBBWPBFFWPPPPFPPPPPPPPUUUUURPPPPPFBPBBBBFPPPPPPPPPPPPPRUUUUUPPPPPFBBBBBBFPPPPPPPPPPPPPRUUUUPPPPPPPBBBBFFYPPPPPPPPPPPPPUUUUPPPPPPPPPFBBBBBBPPPPPPPPPPPRUUUUPPPPPPPPPPBBBBWFPPPPPPPPPPPRUUUURPPPPPPPPPPPPPPPPPPPPPPPPPPPUUUUURRPPPPPPPPPPPPPPPPPPPPPPPPRUUUUUUURPPPPPPPPPPPPPPPPPPPPRRUUUUUUURUUPPPPPPPPPPPPPPPPPPPRUUUUUURRRPPPPPPPPPPPPPPPPRRPPPPUUUUUUURPPPPPPPPPPPPPPPPPPUUPPPPUUUUUUU'

export const santa =
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBUUUUUUUUBBBBBBBBBBBBBBBBBBBBBBYYYYYYUUUUUUBBBBBBBBBBBBBBBBBBBKKKKKKKKKUUUUUUBBBBBBBBBBBBBBBBYKKKKKKKKKKUUUUUUBBBBBBBBBBBBBBBAAAAAAAKKKKUUUUUUUAABBBBBBBBBBBBAABBBBDAAKKKKKKKKKAABBBBBBBBBBBBAPPBPPBBAAKKKBBBBBBBBBBBBBBBBBBBABBBBBBBBAKBBBBBBBBBBBBBBBBBBBBBAPPBPPBBBABBBBBBBBBBBBBBBBBBBBBBABBJBBJBBABBBBBBBBBBBBBBBBBBBBBBAABBBBJBAABBBBBBBBBBBBBBBBBBBBUUAAAAAAAAAABBBBBBBBBBBBBBBBBBBUUKAAAAAAAAAAYBBBBBBBBBBBBBBBBBUUUKAAPPAAAAAKKBBTHBBBBBBBBBBBBUUUKKAAAAAAAAAKBBTJPHBBBBBBBBBBUUUUKKAAAAAAAAAKBBTPUUHBBBBBBBBBUUKUKKKAAAAAAYKKBTPJUUUHBBBBBBBUUUKUJKKAAAAAKKKKBPBBUUUTHBBBBBBBBBJUJKKKKKYKKKKBVBBBUUUTHHBBBBBBBBJUUJKKKKKKKKBBBBBBUUUTHHBBBBBBBHAAUUJKKKKKKJBJBBBBUUKTTHHBBBBBBBPPAAUJKKKKJUVJBBBBKKJTTHHHBBBBBBKPPPAAATTTDAAAVVBPPPTUTTTTBBBBBBBKPPPPPTPTPPPPPPVVVTTTVTTJBBBBBBBBKKKPPTTTPPKKPVVVTTVTTTJJBBBBBBBBBKKKKKJKKKKJBVVVJTTTTJJJBBBBBBBBBBKKKKAKKKJBBBVVJJJJJJJBBBBBBBBBBBBAAABAAABBBBBVVJJJJJBBBBBBBBBBBBBPPPBPPPBBBBBBBBBBBBBBBBBBBBBBBPPPPPBPPPPPBBBBBBBBBBBBBBBBBBBBPPPPPPBPPPPPPBBBBBBBBBBB'

export const marilynMonroe =
  'AADQQDQQQMMHHTHHTHHMMQQQDQQQQDAAADQQQQDDHHHHHHTTHHTHHMQDQQDDQQDADQQDDQMHHTTTTZZZHHTTHHFQQQQQDQQDQQDQDMZHHZZTTTZYTTHHHHMDDDQQDQQDQQQFHHTTTZVZHHTZTTHHHHHHHHHDQQDQDDQXZHHHVZZZHHHHHHTTTHHHHTHHMQQQQQDYFTTHVZHTTTHTTHHTTHHTHTTHMDQQQQQFHHTHZWHHHHTHHHWWHHHHHHTTHDQQQDQFZHHTHMWBBBHBBBBBBBHTHTTHZWQDQQDXVZZTHBBBBBWWBBBBBBWTZHHHZFQQDQQFZZSZWBBBBBBBBBBBBBWHZHHZVODQQDDFVZFJXBBBBBBBWBWWBBBHZTHZVYDQQQMHZVYWBBBBBBBBBBBWBBWZZTHHZWQQDQMHVJWWYXWBBBWXXLXXWWWZHHTTZZQDQQMZVJSMMMXMBBBMMMMMXLZZZHZZZFQQQQWZFOJXQQXBBBBXQDDFYYFZZTZZZVDQDQQZZZVPSYWMBBWXFCRYFFYWZZZJVWQQQDDFVZWMMBBBBBBBBXYXMMXFZZHSJMQQQQDYVZMBBBBBBBBBBBBBBXYVVZZSJFQDDQQQZTWBBBWBBXXBBBBBXVJJZHVRFMQDQQQQZZLBBBXXXLXBBBBWYPBBZZJRFMQQQDDQFFVWBBWYVYXBBBBWVPVFZHYJPOQDQQQQXCJWBBBMMBMBBWXXVPCSVZVSJQDQQDQQDQVXBXYVYYVVBBBWYJCYJRPCMQQQDQDQQMVYBWRFBMORBBWMYJJOJPQQQQQDQQQQDXPYWBYJVVVBBBBXYPPPRFQQDDQQQDQDQQORXWMYLXWBBWXYSPJPPYQQDQQDQQQDQQDJVXBBBBBBWXYJPCFOJOQDQQDQQDDQQQDQFYMBBBBWYVPPPODQQQQDQQDQDQQQDQQQMPOLYXXJPPPJCOQQQXQQDQQDAQQDQQDQQQRPPPPPPJYXXQQDQQQQDQDAAADDQQQDQQRRPPPPRFWMMXQQDQDQQDAA'

export const elephant =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMFFXBAAAAAAAAAAAAAAAAAAAAAAAAABFDAADFDAAAAAAAAAAAAAAAAAAAAAMFMQBBAAABFBAAAAAAAAAAAAAAAAAAAFMAAAAABBAABFAAAAAAAAAAAAAAABBBMFAABAABBBBDBMDAAAAAAAAAAAMFFMMMMDAAABDBBDFFBDXAAAAAAAAAMMBAAAADDMAAABMDDBMMBDFAAAAAAAAMDAAAAAABDMAAABMMDBBDABFAAAAAAAMBAAAAAAABDMMAAAMFDBBBBBQAAAAAAMMAAAAABAABBDMMAAAMBDDBBAFBAAAAAFDAABBABBABBDFFQBBABMMDBBDXAAAAMMBABAABADBBGBBDMMMDDDFBADBFDAAAFDBABBDBADGDDBBBBDDBFFQMBDBDMAAFQBBDDBBBDBBBDDDBDBDBQAMMOMBDFAAFXBDBBDGDDGDBMMDBDMBBFABADFBBQAAFBQBBDDBBMMMMMMMMMDDBOAAAAMMMQMFDAMXMDMMDMMFFDMMDMMMBOAAAABQBFAAAAAOMBDMDMMDMMMDFMMDBOAAAAAQBLAAAAAOBBDFFFQQLQOQXQMDBOAAAAAFMQAAAAAOBBWMMXXAAAAFXQMBBOAAAABFBFAAAAALDDFMDOAAAAAFFLMDBFAAAABXMXAAAAAOMBFXQMAAAAAQFOMBBOAAAAMMFDAAAAAOBBFMQAAAAAALXOMBBOAAOOOBQAAAAAAFBBXMQBAAAAAOXOXBBFAALBBMMAAAAAAOBBMDMOAAAABQWOMBDMMAMFQXBAAAAAALDDMDBFBAAABFXXFDABOAAAAAAAAABBDFOFOOOLMMMMMQOOOOOOLXMDBBAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA'

export const emoji =
  'AAAAAAAAAAAAAAAAAAADDDAAAAAAAAAAAAAAAAAAAAAAAAAAAADBADDAAAAAAAAAAXVVYBWVVVVYMAAAAADDAAAMAAAAAAAAVVVUVVVULVVVVVBAAAMAAADAAAAAAAAAVULLZULLLULUUVVMAADDADBAAAAAAAAAVULUZULZUZLUVLVVBAABDDAAAAAAAAAAUVVUVLUUUZUZVUVVVAAADBAAAAAAAAAALVVVVVVVLVVULVUUVMABDBAAAAAAAAAAVVVZBLVVVUVVUVLVVLABADAAAAAAAAAAVZBAHAHWLVVVVVUVVVADADAAAAABDDDABBBBAAAAHABMLVVVUVDDABDBBADDAADDHBWWMHBBHBWWHWVVVJBBDBAADDDAAAAMMBMMMMBAMMMMMWZVVVDDADDBAABDAADDMBJJBMAAWBJJBMWJVVYBADAAAAADMDDABBBBBBAHHBBBMBHJVVVBABAAAAAAAAAAHHBABHAABABBHBWJVVVADAAAAAAAAAAABBBHAHWWHBAAHHLJUVYADAAAAAAAAAAAHHBBABBBAHHBBHVJVVLBMYAAAAAAAAAALHHBBAHBABHHBLRVUVMDFRYAAAAAAAAARWHBVJJJRVBHWJRVUVMDVJRVAAAAAAAARVWHWLVVLHBWVJJVVVDWJVJRVBAAAAAAJRVWLBLLBLWVRRVUVVDVVVJJRRMAAAAAJRJRZWBLWZJRJJJVUVVVUVVJRRRAAAAARRRRZZZLZZRRRJJJVUUVVVVVJRVAAAAALXXXWWWWHXLXLVJJJVVUVUUVRRAAAAAAXXBXXBBHBXXBXXXYVJVVVLVVRBAAAAAABBBBXBBHBXBBBXXXXVVVUVVJWAAAAAAABBXBBXBBXBBBBBXXXYRVVVRXAAAAAAAABBBBXXXXXBBXBBBBXXRJRRMAAAAAAAAABBBBBBXXBBBBBXBBXXMRYAAAAAAAAAAABBXXBBBBBBXBBBBXBXAAAAAAAAAAAAAABBBBBXBBXBBBXBBXBXAAAAAAAAAAAAAA'

export const rubixCube =
  'DBDDBDDBDDBDDBDDBDDBDDBDDBDDBDDBDBDBBDBBDBBDBBDBBDBBDBBDBBDBBDBDDBGGDBGDBGDBGDBGDBGDBGDBGDBGDBBDBDBGGBGGBGGBGGBGGBGGBGGBGGBGGGDBDGGDBGDBGDBGDBGDPGDBGDBGDBGDBGGGDBGGGGGGGGGGGGPPEPPDGBGGGGGGGDBDDBGGDBBDGBDGPPEEEEEPPDDBBDGBGGBDBDGBGGGGGGPPEEPEEEPFFPPDGBGDGBGGBDGGGDGBPPEEEEEPPPFFFFFPPGDGBDGBDGBDBBPPUUPPEPPUUUPPFPPTTPPGDGBDDBGGPPUUUUUPPPUUUUUPPPTTTTTPPGDGDBGGPBPPUPPUUUPUUUPUUUPPTPPEPDBBBDGBPBBBPPUUUUUPPPUUUUTPPEEEPDBDBDGDPBBBPBPPUPPTTTPPTPPFPEEEPDBGDGBGPBBBPBBBPPTTTTTPPFFFPEEEPDDBDBGGPPBBPBBBPFPPTPPUPFFFPEEPPBDBDBGDPTPPPBBBPFFFPUUUPFFFPPPBPBDGBDGBPTTTPPBBPFFFPUTUPFFPPBBBPDBGBDGGPTTTPEPPPFFFPUUUPPPGPBBBPGBDDGBDPTTTPEEEPPFFPTUPPGBBPBBBPBDGDBGDPPTTPEEEPUPPPPPTPBBBPBBPPDGBDBGGPFPPPEEEPUUUPTTTPBBBPPPTPGGDBDGBPFFFPPEEPUUUPTTTPBBPPTTTPDBGBDGDPFFFPBPPPUUUPTTTPPPUPTTTPDGBDGBGPFFFPBBBPPUUPTTPPUUUPTTTPGDDDBGGPPFFPBBBPUPPPPPBPUUUPTTPPGBGDBGDDGPPPBBBPUUUPBBBPUUUPPPGDDGBBDGBGDGGPPBBPUUUPBBBPUUPPGDDGBDDBDGBGDDDBBPPPTUUPBBBPPPBDDBBGGBGDGGGGBBGDDGGPPUTPBBPPBDDBDGGDGBDDBBDGGGGGGBDDDPPPPPGDDBDBBGGBGGDDGGGBGDBGGGGBDGDBBDBBDBGDGGDBGGB'

export const donaldTrump =
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEEEEPEEEPEEEPEEBBBBBBBBBBBBBBBEEZZZXZZXZZXWHHHHPEEEPBBBBBBBBBEZWWZWWHHZHZZZZHHHHHHZPBBBBBBBBEWWHHHHHZZZHWZZZZZHHHZHPBBBBBBBEZZHHHZZZZYYYZHWZZHHZHHZPBBBBBBEWZZHZHZZZZYVYYZHZZHZZZZYPBBBBBBEZZWHZZZZYYYZZYVZZZZZZZVPBBBBBBEZZZZZZZZZYVZXXXZXZZXZZXPBBBBBBBEYYYYZZZYYYZXWWXXXXXXXXXXPBBBBBBPYYVZYYYVZXXWWWVVVVVWVXVYPBBBBBBPZYYYVZXXXWWWWYZZZXHYWVHZYEBBBBEYZZVVYXXWWWWWWYVZZZZVXYZZZPBBBBEYZVBBHXVVVVVXYVVYYVYXXVVYPBBBBBPYYBWXXHXWWHWWYBBYYVVXXWYVPBBBBBEZVWXXXWXWWWWXXBBMVYYXXWBVEBBBBBEZYWXXZXWWWWHWWWBBWBBXZWBYXPBBBEZZYWXXXXWWWWBWXXWXXWXWWWHBVPBBBPYZVWWZXXWXWWWWWWHHBHHWWWBBXPBBBPYYYYWWXZWXWWWHWWBBHBBWXWWHBPBBBBPYYVVWWWWXWHWWWWBBHBWXXVWBBPBBBBBPYYXYVYXXWWWWBWWWWWXXVXXVYPBBBBBBPPPXWVXXXWWWWWHWWXXWWWWWWPBBBBBBBBBPBWWXXWWBWWWWXWWWYYVYWPBBBBBBBBBEWWWXZXWWWBWWWWWPMDDYXPBBBBBBBBBBPBWXXXXWWWWBWWPYYVVXPBBBBBBBBBBBBEWXXZXXWWWWWBPYVVXPBBBBBBBBBBBBBBPXXZXXXWHWWWXPPXPBBBBBBBBBBBBBBBBPXXXZXXXYWWBBXXPBBBBBBBBBBBBBBBBBPPXXXZXXVWBBWPBBBBBBBBBBBBBBBBBBBBPPPPPPPPPPPBBBBBBB'
