export const HEADER_HEIGHT = 50

export const GAME_MODE_ARCADE = 'GAME_MODE_ARCADE'
export const GAME_MODE_TIMETRIAL = 'GAME_MODE_TIMETRIAL'
export const GAME_MODE_SURVIVAL = 'GAME_MODE_SURVIVAL'
